name: Nightly Build

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:

  Palladio-Addons-ContextConfidentiality-Metamodel:
    if: success() || failure()
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.2
    with:
          deploy-updatesite: 'releng/org.palladiosimulator.pcm.confidentiality.context.updatesite/target/repository'
          java-version: 17
          use-display-output: true
          no-caching: true
          runner-label: ubuntu-latest
    secrets:
          SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}

  Palladio-Addons-ContextConfidentiality-Analysis:
    needs: [Palladio-Addons-ContextConfidentiality-Metamodel]
    if: success() || failure()
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.2
    with:
          deploy-updatesite: 'releng/org.palladiosimulator.pcm.confidentiality.context.analysis.updatesite/target/repository'
          java-version: 17
          use-display-output: true
          no-caching: true
          runner-label: ubuntu-latest
    secrets:
          SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}

  Palladio-Bench-Product-AttackerPropagation:
    needs: [Palladio-Addons-ContextConfidentiality-Analysis]
    if: success() || failure()
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.2
    with:
          deploy-updatesite: 'products/org.palladiosimulator.product/target/deploy'
          java-version: 17
          use-display-output: true
          no-caching: true
          runner-label: ubuntu-latest
    secrets:
          SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
